### ISSUE TITLE
Some bugs I found

### ISSUE THREAD

**Issue by valkyrienyanko** [KirilChingarov/2D-Top-Down-RPG-on-Unity#13] opened 2021-06-02 06:21 UTC
## Project Load
These messages popped up on loading the project.
![image](https://user-images.githubusercontent.com/6277739/120432876-26ba5100-c340-11eb-8384-0430e20a0bb3.png)

## Scene Transition White / Black Flash
When I transition to different levels / zones, there is a white flash on screen for a split second. Sometimes it's a black flash.

![image](https://user-images.githubusercontent.com/6277739/120433321-b2cc7880-c340-11eb-832b-8e48752aed59.png)

Can't progress any further, I get error in console :(

**Comment by KirilChingarov** [comment] 2021-06-02 06:34
Thank you very much for testing my project and reporting the bugs you have found.

The Scene transition with the white/black flash is now fixed.

The error in the console when trying to progress further was caused by a missing reference and is now fixed.

The project load messages are mostly generated by the A* pathfinding package when loading the project for the first time.

**Closed as completed** 2022-03-20 13:57 UTC
